-- Limpa Banco
drop table OrderDetails;
drop table Orders;
drop table Shippers;
drop table EmployeeTerritories;
drop table Territories;
drop table Region;
drop table Employees;
drop table CustomerCustomerDemo;
drop table CustomerDemographics;
drop table Products;
drop table Categories;
drop table Customers;
drop table Suppliers;

-- Tabelas
create table CustomerDemographics(customerTypeID varchar(10) primary key, customerDesc varchar(255) not null);
create table Region(regionID integer primary key, regionDescription varchar(50) not null);
create table Categories(categoryID integer generated by default as identity(start with 1, increment by 1) primary key, categoryName varchar(15) not null, description varchar(255), picture clob(64000));
create table Suppliers(SupplierID integer generated by default as identity(start with 1, increment by 1) PRIMARY KEY not null, CompanyName varchar(40) not null, ContactName varchar(30), ContactTitle varchar(30), Address varchar(60), City varchar(15), Region varchar(15), PostalCode varchar(10), Country varchar(15), Phone varchar(24), Fax varchar(24), HomePage varchar(255));
create table Shippers(ShipperID integer generated by default as identity(start with 1, increment by 1) primary key not null, companyName varchar(40) not null, phone varchar(24));
create table Territories(territoryID VARCHAR(20) not null primary key, territoryDescription varchar(50) not null, regionID integer not null references Region(regionID));
create table Employees(EmployeeID integer primary key, LastName varchar(20) not null, FirstName varchar(10) not null, Title varchar(30), TitleOfCourtesy varchar(25), BirthDate timestamp, HireDate timestamp, Address varchar(60), city varchar(15), region varchar(15), postalCode varchar(10), country varchar(15), homePhone varchar(24), extension varchar(4), photo clob(64000), notes varchar(32000), reportsTo integer references Employees(EmployeeID), photoPath varchar(255), bonus integer default 0);
create table EmployeeTerritories(EmployeeID integer not null references Employees(EmployeeID), territoryID VARCHAR(20) not null references Territories(territoryID));
create table Customers(customerID VARCHAR(5) not null primary key, CompanyName varchar(40) not null, ContactName varchar(30), ContactTitle varchar(30), address varchar(60), city varchar(15), region varchar(15), postalCode varchar(10), country varchar(15), phone varchar(24), fax varchar(24));
create table CustomerCustomerDemo(customerID varchar(5) not null references Customers(customerID) primary key, customerTypeID varchar(10) not null references CustomerDemographics(customerTypeID));
create table Products(productID integer generated by default as identity(start with 1, increment by 1) not null primary key, productName varchar(40) not null, supplierID integer references Suppliers(supplierID), categoryID integer references Categories(categoryID), quantityPerUnit varchar(20), unitPrice decimal(31, 2), unitsInStock integer, unitsOnOrder integer, ReorderLevel integer, disconstinued integer not null);
create table Orders(orderID integer generated by default as identity(start with 1, increment by 1) primary key not null, customerID VARCHAR(5) references Customers(customerID), employeeID integer references Employees(EmployeeID), OrderDate timestamp, requiredDate timestamp, shippedDate timestamp, shipVia integer references Shippers(ShipperID), freight decimal(31, 2), shipName varchar(40), shipAddress varchar(60), shipCity varchar(15), shipRegion varchar(15), shipPostalCode varchar(10), shipCountry varchar(15));
create table OrderDetails(orderID integer references Orders(orderID) not null, productID integer references Products(productID) not null, unitPrice decimal(31, 2) not null, quantity integer not null, discount real not null, PRIMARY KEY(orderID, productID));
